apiVersion: 'v1'
kind: 'Service'
metadata:
  name: 'service-myteam-docker-daemon'
  namespace: 'jenkins-myteam'
  annotations:
    fluxcd.io/automated: 'true'
spec:
  selector:
    app: 'myteam-docker-daemon'
  type: 'ClusterIP'
  ports:
    - name: 'docker-daemon-socket'
      port: 2375
      targetPort: 2375
      protocol: 'TCP'
