unclassified:
  globalConfigFiles:
    configs:
      - mavenSettings:
          id: maven-settings-nexus-zl
          name: maven-settings-nexus-zl
          isReplaceAll: true
          serverCredentialMappings:
            - serverId: snapshots # Used for pull & push on repository snapshots
              credentialsId: 'private-nexus-credentials'
            - serverId: releases # Used for pull & push on repository releases
              credentialsId: 'private-nexus-credentials'
          content: |
            <?xml version="1.0" encoding="UTF-8"?>
            <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
              <pluginGroups>
              </pluginGroups>
              <proxies>
              </proxies>
              <servers>
              </servers>
              <mirrors>
                <mirror>
                  <id>maven-central-mirror</id>
                  <mirrorOf>central</mirrorOf>
                  <name>Maven central mirror</name>
                  <url>https://central-mirror.myorg.com/maven-central-remote</url>
                </mirror>
              </mirrors>
              <profiles>
              </profiles>
            </settings>
